//Basic Loop
//Example 1: Display a Text Five Times
const n=5;
for (let i=1; i<=n;i++){console.log('to the five')};
//Example 2: Display a Text as number in five time
const m=6
for (let i=1; i<=m; i++){console.log(i)};


//Display sum of N Natural NUmbers ********************
let sum = 0
const s = 100
for (let i=1; i<=s; i++){sum+=i}
//another independet example by me
let sunny = 0
const sam = 100
for (let i=1; i<=sam; ++i){sunny+=i}
console.log('sunny:',sunny);
//another
let sarvado = 0
const sarvado1 = 1000
for(i=2; i<=sarvado1; ++i){sarvado+=i}
console.log(sarvado)
// JS for..in Loop
























